dataset: enron
exp_tag: fmgad_enron
ae_alpha: 1.0
ae_dropout: 0.2
ae_lr: 0.003
hid_dim: null
proto_alpha: 0.01
residual_scale: 15.0
sample_steps: 1
score_smoothing_alpha: 0.45
use_virtual_neighbors: true
weight: 0.0
num_trial: 1
polarity_consensus_threshold: 0.7
polarity_consensus_score_weight: 0.95
polarity_enabled: true
